name: Build and Publish

on:
  workflow_dispatch:


jobs:
  job-a:
    name: job-a
    runs-on: ubuntu-latest
    steps:
    - run: echo "Job A"

  job-b:
    name: job-b
    needs: [job-a]
    runs-on: ubuntu-latest
    steps:
    - run: exit 15
  
  job-c:
    name: job-c
    needs: [job-b]
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo "Job C"
       echo ${{ needs.job-b.result }}
      

  test-job-c:
    name: test job
    needs:  [job-b,job-c]
    runs-on: ubuntu-latest
    steps:
      - name: check retry
        run: |
          RUN=${{ github.run_attempt }}
          echo $RUN
          if [[ $RUN -ne 3 ]]; then
            exit 22;
          else
            echo "SUCCESS"
          fi
           
  retry-on-failure:
      if: ${{ failure() && needs.test-job-c.result == 'failure' && github.run_attempt < 3 }}
      needs: [test-job-c]
      runs-on: ubuntu-latest
      steps:
          - run: echo ${{ needs.test-job-c.result }}
          - run: echo ${{ github.run_attempt }}
          - uses: actions/checkout@v4
          - env:
                GH_REPO: ${{ github.repository }}
                GH_TOKEN: ${{ secrets.TOKEN }}
            run: gh workflow run new_retry.yaml -F run_id=${{ github.run_id }}
