name: Retry workflow

on:
    workflow_dispatch:
        inputs:
            run_id:
                required: true
                type: string
#   workflow_run:
#     workflows: [Auto Deploy to CI]
#     types: [completed]
#     branches: main
jobs:
    rerun:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - uses: actions/checkout@v4
            - name: rerun ${{ inputs.run_id }}
              env:
                  GH_REPO: ${{ github.repository }}
                  GH_TOKEN: ${{ secrets.TOKEN }}
              run: gh run rerun ${{ inputs.run_id }} --failed