name: Retry workflow

on:
    workflow_call:
        inputs:
            run_id:
                required: true
jobs:
    rerun:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: rerun ${{ inputs.run_id }}
              env:
                  GH_REPO: ${{ github.repository }}
                  GH_TOKEN: ${{ secrets.TOKEN }}
              run: gh run rerun ${{ inputs.run_id }} --failed