name: Test Var

on:
  workflow_dispatch:
    inputs:
      input1:
        description: Job 1 Input
        type: string
        default: Simple Job 1

      input2:
        description: Job 1 Input
        type: string
        default: Crack Job 3
      
      input3:
        description: Job 1 Input
        type: string
        default: Puffer Job 1

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: job-1
        run: echo "This is JOB1"
      - name: job-1a
        run: echo ${{ inputs.input1 }}

  job_two:
    runs-on: ubuntu-latest
    steps:
      - name: job-2
        run: echo "This is JOB 2"
      - name: job-2a
        run: echo ${{ inputs.input2 }}

  job_three:
    runs-on: ubuntu-latest
    steps:
      - name: job-3
        run: echo "This is JOB3"
      - name: job-2a
        run: |
          echo ${{ inputs.input3 }}
          exit 22

  rerun-failed-jobs:
      runs-on: ubuntu-latest
      needs: [ job_two, job_three]
      if: failure()
      steps:
        - name: Rerun failed jobs in the current workflow
          env:
            GH_TOKEN: ${{ github.token }}
          run: gh run rerun ${{ github.run_id }} --failed